# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-05 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('code', models.CharField(max_length=3)),
                ('active', models.BooleanField()),
                ('category', models.CharField(max_length=9)),
            ],
        ),
    ]
